### ISSUE TITLE
Support own API URL for locally hosted Models

### ISSUE THREAD

**Issue by VfBfoerst** [neary-ai/neary#2]
Thank you for this project, seems to be one of the most promising Chat UIs :}   
Is there a way to configure an own URL for the API? We are hosting a llama.cpp API with is compatible to the openAI-API, so it shouldn't be a problem to just change the URL. Would be a nice feature if it isn't implemented yet :} Thank you!

**Comment by mightworks** [comment]
Hi there, thanks for checking out Neary :). This is actually next up, along with a LocalAI integration. Should be in the next couple of days!

**Comment by VfBfoerst** [comment]
Awesome, thank you :)  
How do you set the API URL from openai at the moment? I tried grepping some Strings but could Not find it yet :/

**Comment by mightworks** [comment]
The URL isn't exposed, but you can set it to anything you want by setting the OPENAI_API_BASE variable in the .env file

**Comment by VfBfoerst** [comment]
Nice! I will try that :}

**Comment by mightworks** [comment]
This is complete, thanks for the feedback!

You can set your local endpoint in the .env file now:

`# Local setup via LocalAI or other "drop-in" OpenAI API replacements
LOCAL_ENDPOINT=http://localhost:8080/v1`

Then, in your conversation settings, you can select which endpoint you want to use. There's also a new program added called 'Local Chat' that defaults to the local API endpoint and doesn't include any fancy tools/capabilities out of the box. Just the system message (which you can also modify in conversation settings).

**Comment by VfBfoerst** [comment]
@mightworks Is the openai api token still required? After starting the containers with docker-compose, I cannot login. After Account creation, I am getting an error 401 unauthorized when I try to login with the initially created account. Or is another default account configured?

**Comment by mightworks** [comment]
@VfBfoerst Hi there, none of the recent changes affected the database, so the login you initially setup should still work after you pulled the new changes. Are you getting an error message on login, like invalid email / password?

I just pushed a bit of a networking fix that'll help Neary talk to other services like (like local apis) on localhost. Give these steps a shot and let me know if you're still having trouble.

Pull the latest changes:
```
git pull
```

If you need Neary to access your local model on localhost, you should replace 'localhost' with 'host.docker.internal' in the .env file like this:

```
LOCAL_ENDPOINT=http://host.docker.internal:8080/v1
```

Rebuild and launch the container:

```
docker compose up --build
```

For good measure, clear your cookies or logout before you do anything else (http://localhost:8000/logout)

Then, go to http://localhost:8000. If you've already created an account, it should present you with a login screen. Use your original account info and you should be all set.

Also, no OpenAI API key is required. You'll just get an error if the api type is set to anything other than 'local' in settings for any given conversation.

Finally! I'm implementing an option to disable authentication, since a lot of people running locally don't need it. If you're still having issues this may be a good option.

Let me know how it goes and any errors you run into!

Joe

**Comment by VfBfoerst** [comment]
I re-enabled authentication, but it still does not work. After creating a new account (I removed all data from the docker volume to start a fresh new instance), the Login-Page shows up. When I enter my previously created credentials, the page refreshes without any status message. On the logs, I get the following message:   
  
`GET /api/initialize HTTP/1.1" 401 Unauthorize`
